# Generated by Django 5.0.2 on 2024-02-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kai_user_name', models.CharField(max_length=100)),
                ('kai_password', models.CharField(max_length=50)),
                ('kai_insert_time', models.DateTimeField()),
                ('kai_updated_time', models.DateTimeField()),
            ],
        ),
    ]
