# Generated by Django 5.0.2 on 2024-02-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='kai_user_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
