# Generated by Django 5.0.2 on 2024-02-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizn', '0002_remove_users_id_alter_users_kai_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kai_SKU', models.CharField(max_length=20)),
                ('kai_Name', models.CharField(max_length=50)),
                ('kai_Category', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
