# Generated by Django 5.0.2 on 2024-02-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizn', '0003_items_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('kai_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('kai_password', models.CharField(max_length=50)),
                ('kai_insert_time', models.DateTimeField()),
                ('kai_updated_time', models.DateTimeField()),
            ],
        ),
    ]
