# Generated by Django 5.0.2 on 2024-02-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizn', '0004_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
