# Generated by Django 5.0.2 on 2024-02-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kaizn', '0005_delete_items_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('kai_SKU', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kai_Name', models.CharField(max_length=50)),
                ('kai_Category', models.CharField(max_length=20)),
                ('kai_instock', models.IntegerField()),
                ('kai_available_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('kai_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('kai_password', models.CharField(max_length=50)),
                ('kai_insert_time', models.DateTimeField()),
                ('kai_isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kai_tags', models.CharField(max_length=20)),
                ('kai_SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaizn.items')),
            ],
        ),
    ]
