# Generated by Django 5.0.2 on 2024-02-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizn', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='kai_insert_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='kai_isactive',
        ),
    ]
